Add friends likes
maershov/java-filmorate pull request #4
Opened 2023-05-20 12:14 UTC by maershov

2023-05-21 00:39 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    public List<User> getAllUsers();
у интерфейса и так все методы public. Можно не писать public

2023-05-21 00:52 UTC, EvgenyKoptubenko commented
Если отправить такой запрос
curl --request POST \
  --url http://localhost:8080/films \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name":"FilmName",
	"email":"email@email.com",
  "login":"login",
	"birthday":"2001-01-01",
	"description":"film Description",
	"duration":22
}'

{
	"error": "Interval Server Error",
	"description": "JSON parse error: Cannot construct instance of `ru.yandex.practicum.filmorate.model.Film`, problem: releaseDate is marked non-null but is null; nested exception is com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `ru.yandex.practicum.filmorate.model.Film`, problem: releaseDate is marked non-null but is null\n at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 8, column: 1]"
}
То приходит ответ, в котором слишком много информации. Считает несекурно показывать внутренности приложения при ошибках

2023-05-21 00:54 UTC, EvgenyKoptubenko requested changes
Работа сделана отлично. Есть немного предложений по улучшению кода

2023-05-21 00:54 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/conrollers/UserControllerTest.java
>      public void userCreatePositiveTest() {
У тестов методы могут быть без модификатора public

2023-05-21 00:54 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/conrollers/UserControllerTest.java
>      public void userCreatePositiveTest() {
Если есть желание, попробуй прараметризованные тесты - это сократит количество кода
https://www.baeldung.com/parameterized-tests-junit-5

2023-06-06 13:27 UTC, Umka7389 reviewed
Молодец, отличная работа!

2023-08-14 17:49 UTC, merged